[package]
name = "dedupfeed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
time = "0.1.44"
rust-crypto = "0.2.36"
sha2 = "0.10.6"
hex = "0.4.3"